# The URL the site will be built for
base_url = "https://srg.id.au"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
minify_html = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feeds = true

taxonomies = [
    { name = "tags", feed = true }
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "Solarized (light)"
extra_syntaxes_and_themes = ["syntaxes"]

[extra]
site_title = "Shaunak Gadkari"
site_description = "Medical student and developer from Melbourne"
newsletter_subscribe_endpoint = "/api/subscribe"
